[tool.black]
line-length = 79
skip-string-normalization = false
exclude = '''
/(
    \.git
  | \.venv
  | build
  | dist
)/
'''
[tool.isort]
profile = "black"
line_length = 79
known_third_party = "fastapi"
skip = [
    ".venv",
]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.flake8]
max-line-length = 79
exclude = '''
/(
    \.git
  | \.venv
  | build
  | dist
  | migrations
)/
'''
ignore = "E203,E266,E501,W503,F401"


[tool.mypy]
python_version = 3.12
check_untyped_defs = true
ignore_missing_imports = true
warn_unused_ignores = true
